version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.25
    commands:
      - echo "Using Go version:"
      - go version
      - echo "Using Docker version:"
      - docker version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - echo "Git commit hash: $COMMIT_HASH"
      - IMAGE_TAG=${COMMIT_HASH}

  build:
    commands:
      - echo "Building Docker image with commit hash tag..."
      - cd $CODEBUILD_SRC_DIR
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Updating ECS task definition with commit hash..."
      - TASK_DEF=$(aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION --region $AWS_DEFAULT_REGION)
      - TASK_DEF_ARN=$(echo $TASK_DEF | jq -r '.taskDefinition.taskDefinitionArn' | sed 's/:[0-9]*$//')
      - NEW_TASK_DEF=$(aws ecs register-task-definition --cli-input-json "$(echo $TASK_DEF | jq --arg image "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG" '.taskDefinition.containerDefinitions[0].image = $image | del(.taskDefinition.taskDefinitionArn, .taskDefinition.revision, .taskDefinition.status, .taskDefinition.compatibilities, .taskDefinition.registeredAt, .taskDefinition.registeredBy)' | jq '.')" --region $AWS_DEFAULT_REGION)
      - NEW_TASK_DEF_ARN=$(echo $NEW_TASK_DEF | jq -r '.taskDefinition.taskDefinitionArn')
      # - echo "Updating ECS service with new task definition: $NEW_TASK_DEF_ARN"
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $NEW_TASK_DEF_ARN --force-new-deployment --region $AWS_DEFAULT_REGION
      - echo "Build completed successfully!"
      # - echo "Deployed image with commit hash: $IMAGE_TAG"