env: local
log:
  level: debug
dynamodb:
  region: local
  # DynamoDB Local endpoint (Docker service name)
  endpointOverride: "http://localhost:8000"
  showsTable: "shows_local"
  createTableIfMissing: true
