env: local
log:
  level: debug
dynamodb:
  region: "ap-southeast-2"
  # DynamoDB Local endpoint (Docker service name)
  endpointOverride: "http://localhost:8000"
  showsTable: "shows-local"
  createTableIfMissing: true
