# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: tidy 
      run: make tidy

    - name: fmt
      run: make fmt

    - name: vet
      run: make vet 
  
    - name: build
      run: make build

    - name: test
      run: make test

    # This step will be fixed later on in the Makefile.
    - name: integration-test
      run: |
        @echo "Starting services..."
        docker compose up -d --build
        @echo "Running integration tests..."
        go test ./test/integration_tests || (echo "Tests failed, stopping services..."; docker-compose down; exit 1)
        @echo "Stopping services..."
        docker compose down
